### ISSUE TITLE
Баг команды инкогнито

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#130]
In GitLab by @Adagium on Jul 12, 2021, 16:14

При использовании команды инкогнито лидером (роль "лидерство") - игрок не может вернуть себе роль. Помогает только перезаход. Не могу быть уверен, что у других ролей с командой инкогнито нет такого же бага.

**Comment by chelog** [comment]
@mikvoin надо выдать этот пермишн всем рангам, включая игрока:

![](https://i.imgur.com/tq0iNq8.png)
