### ISSUE TITLE
Элементы одежды Токо и Мондо видно через стену с буфета на кухню

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#169]
In GitLab by @NeverLucky21 on Aug 2, 2021, 22:29

Title

![image](/uploads/36a678a768312d5859993b602459080b/image.png)

**Comment by octothorpteam** [comment]
In GitLab by @Krou on Aug 3, 2021, 23:14

Проблема связана с тем, что их тела одевались через инструмент Easy Bonemerge Tool

**Comment by octothorpteam** [comment]
In GitLab by @Mikvoin on Aug 5, 2021, 22:26

assigned to @Mikvoin

**Comment by mikvoin** [comment]
Исправлено
