### ISSUE TITLE
Музыка в пустом пресете плейлиста

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#180]
In GitLab by @Mikvoin on Aug 4, 2021, 24:49

- Остается музыка с предыдущего плейлиста:
- ![](https://i.imgur.com/X0HrsnV.png)

**Comment by octothorpteam** [comment]
In GitLab by @Mikvoin on Aug 4, 2021, 24:49

changed the description

**Comment by mikvoin** [comment]
При создании нового плейлиста остается музыка с предыдущего плейлиста. Это очень неудобно.
