### ISSUE TITLE
Свойства энтити открываются через раз

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#223]
In GitLab by @Mikvoin on Aug 6, 2021, 15:20

![2021-08-06_15-12-57](/uploads/257a822459543f8706190bf4b67f0fab/2021-08-06_15-12-57.mp4)

**Comment by octothorpteam** [comment]
In GitLab by @Mikvoin on Aug 6, 2021, 15:20

changed the description

**Comment by octothorpteam** [comment]
In GitLab by @Mikvoin on Aug 6, 2021, 15:21

changed the description

**Comment by octothorpteam** [comment]
In GitLab by @chelog on Aug 18, 2021, 17:29

assigned to @chelog

**Comment by mikvoin** [comment]
Исправлено
