### ISSUE TITLE
Нельзя взять физган/тулган после окончания игры

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#245]
In GitLab by @goldflame on Aug 8, 2021, 24:58

Как и говорилось в заголовке, пропадает физган и тулган после окончания игры. Особо много сказать о баге не могу.

**Comment by octothorpteam** [comment]
In GitLab by @cherrymiku on Aug 8, 2021, 19:32

После окончания игры нельзя не только физган/тулган взять, но и чат открыть, если поменять этап игры через консоль с Конец игры на Подготовку, то все будет работать. Это к слову всему этого)

**Comment by mikvoin** [comment]
https://github.com/danganronpa-online/public-gmod/issues/292
