### ISSUE TITLE
Эмо-спрайты аргументов(У Омы и Миу)

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#289]
In GitLab by @Derevashka on Aug 22, 2021, 22:44

На суде, в 12 эпизоде, спрайты аргументов у Кокичи и Миу у меня оказывались эмо-текстурами. Такими были ТОЛЬКО спрайты аргументов, остальные были в норме

**Comment by octothorpteam** [comment]
In GitLab by @Derevashka on Aug 22, 2021, 22:44

changed the description

**Comment by octothorpteam** [comment]
In GitLab by @Mikvoin on Aug 26, 2021, 12:07

@Derevashka 
Такими были все спрайты опровержения Омы и Миу или какие-то были нормальными?

**Comment by mikvoin** [comment]
Нужно проверить, актуально ли это по сей день.

**Comment by SaintKrou** [comment]
У ВСЕХ персонажей Error аргументы @mikvoin

**Comment by SaintKrou** [comment]
Спрайты опровержения норм

**Comment by mikvoin** [comment]
Исправлено
