### ISSUE TITLE
Тени через этажи

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#306]
In GitLab by @HistoryFedor on Aug 29, 2021, 22:36

Тени персонажей падают через этажи.![dro_hopespeak_3006210007](/uploads/5c7b93305ff0eaaf70f884784d5d10ad/dro_hopespeak_3006210007.png)

**Comment by SaintKrou** [comment]
О данном баге уже сообщено
https://github.com/danganronpa-online/public-gmod/issues/225
