### ISSUE TITLE
Проблемы со спавном

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#314]
In GitLab by @Stalker on Sep 5, 2021, 11:00

После суда игроки появляются в центре/застревают в стойке. При этом способ выбора тех, кто появляется в центре — абсолютно рандомен. Иными словами, в центр может встать кто угодно, даже Монокума![dro_hopespeak_3006210018](/uploads/75de28337ed9f5ed55f8df166d6eb747/dro_hopespeak_3006210018.jpg)![dro_hopespeak_3006210021](/uploads/5b191a8ea209d4f4522e914fa4716cf8/dro_hopespeak_3006210021.jpg)

**Comment by SaintKrou** [comment]
О данном баге уже сообщено
https://github.com/danganronpa-online/public-gmod/issues/297
