### ISSUE TITLE
Интерфейс суда 

### ISSUE THREAD

**Issue by RanamNinja** [danganronpa-online/public-gmod#322]
10.10 числа, на игре "Эпизод 32.1", произошел такой баг на последнем суде : когда голосование закончилось, на экране игроков остался интерфейс суда, а сами игроки не видели друг-друга. Вместе с этим, перед началом голосования, команда, которая меняет статус игры - не работала, и пришлось работать с моно-меню. Происхождение неизвестно, однако, возможно, это связанно с тем, что изначально я написал команду как "setgamestatus executionё" с лишней буквой в конце, и только потом правильно, и с этого момента уже наблюдались неполадки. Ранее наблюдалась проблема, что пропы на сервере проваливались через пол, проходили через стенки, резко улетали в стороны.
![image](https://user-images.githubusercontent.com/92528292/137327843-b0d0dcf1-4bf4-4807-b0da-379b221f45c7.png)

**Comment by mikvoin** [comment]
@RanamNinja, ошибку с проваливанием пропов исправили.  #323

**Comment by SaintKrou** [comment]
Когда во время суда в консоль пишется "setgamestatus executionё" мономеню показывает, что идёт этап казни, однако классный суд продолжается. При попытке написать "setgamestatus execution" меняется музыка, но суд все еще идет. Говорить и нажимать G игроки не могут. Можно начать голосование, на нем не будет музыки, а после него будет музыка казни, но суд будет идти. Вот что происходит при нажатии ["подготовка к игре"](https://i.imgur.com/RDMZk8y.jpeg) и вот что после последующего ["Начать игру"](https://i.imgur.com/nrMgyez.jpeg) (Музыка дня/ночи идет). После этого нажал "Начать классный суд" и все пофиксилось

**Comment by mikvoin** [comment]
Логично, что если написать команду: "setgamestatus executionё", то ничего не будет работать, потому что этап сменяется на подготовку и цикл ломается.
