### ISSUE TITLE
Баг с пропами

### ISSUE THREAD

**Issue by RanamNinja** [danganronpa-online/public-gmod#323]
10.10 числа, на игре "Эпизод 32.1", был замен такой баг ближе к концу игры : пропы, которые не были зафриженны, могли летать по карте, пролетать через стены и пол, а при спауне - резко отлетали в сторону. Происхождение бага неизвестно.

**Comment by mikvoin** [comment]
Было исправлено:
![](https://i.imgur.com/N76Ihdc.png)
