### ISSUE TITLE
Фон на изображении зеленого фона

### ISSUE THREAD

**Issue by SaintKrou** [danganronpa-online/public-gmod#329]
### Что наблюдается?

У изображения Ремы зеленый фон
https://i.imgur.com/eNYAfrX.png

### Как это должно работать?

Зеленого фона не должно быть

### Как это повторить?

1) Начать голосование
2) Взглянуть на Рему

### Ошибки в консоли

```shell
-
```

### Обратная связь

Krou#2034

**Comment by mikvoin** [comment]
Исправлено
