### ISSUE TITLE
Проблемы с Рейко Вакай

### ISSUE THREAD

**Issue by SaintKrou** [danganronpa-online/public-gmod#332]
### Что наблюдается?

У Character6_2 (Рейко Вакай, ОСа) нет изображения на головании, а также изображение в углу и пиксельная иконка аргумента неправильно отображаются
![image](https://user-images.githubusercontent.com/91148905/138913613-d9d20640-770d-4ed6-8606-e27d20efb2fb.png)
![image](https://user-images.githubusercontent.com/91148905/138914234-70aa6858-9ee3-42ea-bac6-4d42590473df.png)

### Как это должно работать?

Нормально

### Как это повторить?

1) Выбрать персонажа character6_2
2) Начать суд
3) Навести на Рейко камеру, увидеть созданный им аргумент
4) Начать голосование и взглянуть на него

### Ошибки в консоли

```shell
-
```

### Обратная связь

Krou#2034

**Comment by mikvoin** [comment]
Не является ошибкой, так как персонаж не является играбельным на данный момент.
