### ISSUE TITLE
Цвет физгана у ранга "Сюжетная роль"

### ISSUE THREAD

**Issue by SaintKrou** [danganronpa-online/public-gmod#341]
### Что наблюдается?

Цвет физгана у сюжетной роли красный, из-за чего видно, что человек хватает предмет физганом
![image](https://user-images.githubusercontent.com/91148905/140621125-153efb12-d77a-4ffb-9f74-5e145f5a1753.png)

### Как это должно работать?

Цвет физгана должен быть прозрачным

### Как это повторить?

1) Выдать игроку ранг "Сюжетная роль"
2) Этот игрок должен взять какой-то проп физганом

### Обратная связь

Krou#2034

**Comment by mikvoin** [comment]
Исправлено
