### ISSUE TITLE
setgamestatus

### ISSUE THREAD

**Issue by cherrymiki** [danganronpa-online/public-gmod#342]
### Что наблюдается?

при вводе setgamestatus day/night полностью ломается цикл дня и ночи, а также не начинается расследование и все песни играют прям до конца, и только после этого начинаются песни из текущего этапа игры, звонок не проигрывается и музыка не меняется в 22:05 на сколько я помню и в 8:00

### Как это должно работать?

ну должны меняться чо)

### Как это повторить?

запустить игру, написать setgamestatus day, поменять время допустим через settime 22:00
звонка не будет слышно а также оповещение о нахождении трупа не сработает

### Обратная связь

cherrymiku#9669

**Comment by mikvoin** [comment]
@cherrymiki у нас нет такого статуса как `day` или `night`. Для подобного используется `game`
