### ISSUE TITLE
Личные записи (Аргументы) имеют Error на иконке, пока их не предъявишь

### ISSUE THREAD

**Issue by SaintKrou** [danganronpa-online/public-gmod#346]
### Что наблюдается?

Созданные аргументы имеют Error иконку. Когда уже показываешь всем, то все норм
![image](https://user-images.githubusercontent.com/91148905/142719420-f85507ec-47cf-4529-a799-33555b97390d.png)

### Как это должно работать?

Должна быть другая иконка

### Как это повторить?

1) Создать аргумент
2) Взглянуть на него либо через Монопад, либо на суду. Иконка - Error

### Обратная связь

Krou#2034

**Comment by mikvoin** [comment]
Исправлено
