### ISSUE TITLE
Иллюстрация Рёмы Хоши на голосовании

### ISSUE THREAD

**Issue by eronique** [danganronpa-online/public-gmod#351]
### Что наблюдается?

скриншот: https://i.imgur.com/RCiSkkw.png

во время голосовании прозрачный фон на иллюстрации рёмы хоши куда-то пропал. это также произошло у меня один раз, поэтому существует вероятность, что проблема клиетская.

### Как это должно работать?

фон должен быть прозрачный!

### Как это повторить?

возможно, стоит проверить иллюстрацию рёмы на суде. если на данный момент всё в полном порядке, то оставить этот баг до повторного проявления чего-то подобного.

### Обратная связь

eronique ☆#4235

**Comment by mikvoin** [comment]
На данный момент этого не наблюдается. Было исправлено в #329.
Можешь перепроверить у себя, @eronique?

**Comment by eronique** [comment]
сейчас проверила, всё окей.
скрин: https://i.imgur.com/XY7Q097.png
