### ISSUE TITLE
Atmos, освещение и постоянные фризы на сервере

### ISSUE THREAD

**Issue by eronique** [danganronpa-online/public-gmod#352]
### Что наблюдается?

уже несколько недель на сервере происходят очень неприятные фризы, которые мешают игре. они проявляют себя как и на хоупспике, так и на других картах.

примеры:
эпизод 52: https://youtu.be/5MyTRU4wng4?t=5450 (1:30:50)
эпизод 49: https://youtu.be/xH8I3CAaTcU?t=22820 (6:20:20)
эпизод 48: https://youtu.be/54fMG-yOPbg?t=1573 (26:13)

по наблюдениям я выяснила, что данную проблему скорее всего принёс к нам atmos. потому что при изменении глобального освещения (светлее днём, темнее ночью) подгружается свет на карте, что вызывает фризы даже у стримеров с хорошим оборудованием. 

### Как это должно работать?

фризов быть не должно, разумеется. не хотелось бы лишаться атмоса, потому что аддон крутой, но от фризов лучше было бы избавиться.

### Как это повторить?

просто подождать изменения освещения. 
также есть вероятность, что проблема может быть не в атмосе.

### Обратная связь

eronique ☆#4235

**Comment by mikvoin** [comment]
Исправлено
![](https://i.imgur.com/meC8DeK.png)
