### ISSUE TITLE
При возвращении игрока в игру после смерти он остаётся в лобби + пропадают руки.

### ISSUE THREAD

**Issue by eronique** [danganronpa-online/public-gmod#353]
### Что наблюдается?

вот пример:
24 эпизод: https://youtu.be/51gHDYp9OHc?t=11160 (3:06:00)
на данном примере стримера **убило пропом**, что произошло случайно, поэтому его пришлось возвращать в игру. при возвращении он остался в лобби, что явно не является нормой.

____

другая ситуация.
пример:
24 эпизод: https://youtu.be/TpkGhI2HsL4?t=4410 (1:13:30)
такая же **смерть от пропа**. после возвращения в игру командой !rettogame персонаж спавнится в лобби, а его руки, физган, админ-тул и тулган пропадают. приходится просить администратора/гма выдавать их отдельно.

после команды !ragdoll происходит такая же проблема. персонаж считается мёртвым для игры, возвращаем его в игру с помощью команды !rettogame и история повторяется.

### Как это должно работать?

было бы замечательно, если бы после использования команды !rettogame персонаж возвращался на место своей смерти, а руки, тулганы, админ-тулы и физганы были на месте.

### Как это повторить?

1. берём персонажа, запускаем игру и прописываем команду !ragdoll ^, затем снова её же, дабы подняться на ноги.
2. затем возвращаем себя в игру командой !rettogame.
3. понимаем, что мы в лобби, а в руках пустота.

тоже самое можно опробовать, убив персонажа пропом.

### Обратная связь

eronique ☆#4235

**Comment by GreedSan** [comment]
Исправлено.
