### ISSUE TITLE
Иконки со спрайтами перепутаны. (Чиаки Нанами)

### ISSUE THREAD

**Issue by FriendlyAngel** [danganronpa-online/public-gmod#354]
### Что наблюдается?

На суде у Чиаки перепутана иконка со спрайтом.

### Как это должно работать?

Вроде как, нужно просто поменять иконки местами, чтобы не было путаницы.
![unknown (11)](https://user-images.githubusercontent.com/94803116/142775762-4e40ed42-3969-403d-aefa-774c14a4e1a9.png)
![unknown (12)](https://user-images.githubusercontent.com/94803116/142775774-b4bfdadf-0c78-48be-9d32-a54f9e6b6dfd.png)

### Обратная связь

Friendly Angel#6148

**Comment by mikvoin** [comment]
Исправлено.
