### ISSUE TITLE
переменная day/night в команде setgamestatus.

### ISSUE THREAD

**Issue by eronique** [danganronpa-online/public-gmod#357]
### Что наблюдается?

уже делали багрепорт на эту тему, поэтому я сделаю ещё один.

![image](https://user-images.githubusercontent.com/94794102/142912509-5a140920-c80c-4dbb-83df-5493b2a62005.png)

на скрине, который находится выше, я сначала ввожу команду **setgamestatus investigation**, а затем **setgamestatus night**.
на скрине также видно, что музыка меняется на ночную (играет из плейлиста с ночной музыкой, а само изображение в худе поменялось на "ночь", хотя время на сервере дневное). вот как это выглядит:

![image](https://user-images.githubusercontent.com/94794102/142913015-91add84b-9221-4124-a44b-6abf17031448.png)

______

и если после этого я хочу переключить на "расследование", то после ввода команды **setgamestatus investigation** музыка не меняется. при нахождении тела музыка также не меняется. хотя сам этап сменился на "расследование".
но если я введу команду **setgamestatus investigation** два раза, то музыка заиграет.

![image](https://user-images.githubusercontent.com/94794102/142913331-217e6f95-1d30-4367-842b-acf342e1d83f.png)

_____

**важно отметить!**

если я уже ввела **setgamestatus night/day**, то переключить на день или ночь после её ввода уже нельзя. 

![image](https://user-images.githubusercontent.com/94794102/142914135-159b89de-ae0b-4463-9f8f-2d97a842d864.png)

но если я снова введу **setgamestatus investigation** два раза, а затем введу **setgamestatus night/day**, то музыка опять поменяется.

![image](https://user-images.githubusercontent.com/94794102/142914518-a55f9ccd-753d-485e-8b5c-fdd5dfe02924.png)

_____

**и ещё одно!**
после каждого ввода команды **setgamestatus night/day** вне зависимости от смены музыки изображение на худе действительно меняется на "день" или "ночь". эти параметры работают, и с ними нужно что-то сделать, наверное?

### Как это должно работать?

я думаю, что параметры **night/day** нужно или исключить, или сделать работоспособными.

как игровой мастер скажу, что с этими параметрами гм'ы смогли бы более организованно реализовывать свои плейлисты и музыкальное сопровождение на играх. но если данные параметры неудобны, то лучше исключить возможность их использования.

### Как это повторить?

я описала всё подробно в проблеме.

### Обратная связь

отвечу здесь.

**Comment by mikvoin** [comment]
@eronique 
`setgamestatus night/day` не должны использоваться от слова совсем. Чтобы переключаться на ночной плейлист, можно использовать `!settime` в чате.
