### ISSUE TITLE
Ерроры новых моделек в3

### ISSUE THREAD

**Issue by Megunee** [danganronpa-online/public-gmod#368]
### Что наблюдается?

На всех серверах новые модельки персонажей в3 -  Еррорки, а если точнее: char8, char10, char13 (Тенко, Рантаро и Кируми). Ни один регдолл персонажей в3 из players4 не спавнится, остальные, кто у меня в этой папке есть - спавнятся. Контент весь скачан, даже переустановлен, однако,  заметила, что этого аддона (players4), нет в общем контенте дро, а есть только в контенте сервера 5, откуда и был скачан. 
![Скриншот 08-12-2021 155519](https://user-images.githubusercontent.com/95756553/145216041-91505b2f-1473-46f1-8e72-cfcf5ddeac59.png)
![Скриншот 08-12-2021 160024](https://user-images.githubusercontent.com/95756553/145216070-d97522c5-f18d-4b85-8fd2-1b28b4adb895.png)
![Скриншот 08-12-2021 154129](https://user-images.githubusercontent.com/95756553/145216113-027ead62-4b24-40b1-a393-8c1447086c22.png)

### Как это должно работать?

Все модельки должны быть видны, players4 должны быть в общем  контенте. 

### Как это повторить?

Зайти на любой сервер, открыть через физган players4. Или же взять персонажа через ф4 (Тенко, Рантаро и Кируми)

### Ошибки в консоли

```shell
Ошибок нет
```

### Обратная связь

https://vk.com/dvammi

**Comment by SaintKrou** [comment]
Отмечу, что у меня перечисленные персонажи не Error, однако с остальным такие же проблемы. Тесты были на серверах  1 и 2

**Comment by mikvoin** [comment]
Исправится после рестарта сервера.
