### ISSUE TITLE
Черный экран у персонажей

### ISSUE THREAD

**Issue by Megunee** [danganronpa-online/public-gmod#369]
### Что наблюдается?

У некоторых персонажей в3 черный экран (на постоянной основе, все становится видно, когда летаешь в ноуклипе), у всех персонажей в3 камера проваливается под пол, когда берешь физган в руки. У половины персонажей все нормально, у другой половины (Рантаро, Корекиё, Тенко, Химико, Кируми, Цумуги) - черный экран, даже когда ходишь.  
![unknown](https://user-images.githubusercontent.com/95756553/145217500-370e689a-a601-427f-b1f2-afe350f0f3b7.png)
![image](https://user-images.githubusercontent.com/95756553/145217550-90e50c14-1b11-430b-a739-2885a14e70e6.png)
![image](https://user-images.githubusercontent.com/95756553/145217989-1f9b0bcf-dd85-4624-8e8d-4d891c9734d1.png)

. 

### Как это должно работать?

Все должно быть видно, камера не должна проваливаться, когда физган в руках. 

### Как это повторить?

Зайти на сервер, взять любого персонажа в3 и взять физган в руки. Так же взять Рантаро, Корекиё, Тенко, Химико, Кируми, Цумуги и увидеть, что экран черный. 

### Ошибки в консоли

```shell
Ошибок нет
```

### Обратная связь

https://vk.com/dvammi

**Comment by mikvoin** [comment]
Дубликат #368
