### ISSUE TITLE
Значок с ошибкой над значком казни

### ISSUE THREAD

**Issue by NeverLucky21** [danganronpa-online/public-gmod#374]
### Что наблюдается?

Над значком "казни" за краем стоит "эрорка".

![image](https://user-images.githubusercontent.com/40503335/145679081-41cf8868-7354-47e7-ac1c-aae11dcd2efe.png)

### Как это должно работать?

Ну желательно если бы этой эрорки не было.

### Как это повторить?

1) Начать игру
2) Начать голосование/!setgamestatus execution
3) Взглянуть на верхний правый угол

### Обратная связь

NeverLucky#6572

**Comment by mikvoin** [comment]
Исправлено
