### ISSUE TITLE
Недочёты у модели Корекиё

### ISSUE THREAD

**Issue by GoldFlame** [danganronpa-online/public-gmod#377]
### Что наблюдается?

1. Небольшой фрагмент одежды без текстуры.

![hl2_pIDw5kio0F](https://user-images.githubusercontent.com/22894602/146527905-48096601-de78-409d-b758-efbe150128d1.png)

2. При увеличении некоторых ползунков в редакторе лица (брови, рот), у модели начинают вылезать текстуры в районе ушей.

![hl2_yeuJEh5qtR](https://user-images.githubusercontent.com/22894602/146528003-61288205-5ed4-4915-a61e-d072920af8dc.png)

### Как это должно работать?

1. Текстуры на одежде должны корректно отображаться;
2. Текстуры не должны ломаться при настройке лица.

### Как это повторить?

1) Взять модель Корекиё;
2) Открыть редактор Facial Emotes;
3) Подвигать ползунки.

**Comment by mikvoin** [comment]
Исправлено
