### ISSUE TITLE
Моделька фонарика не отображается

### ISSUE THREAD

**Issue by NeverLucky21** [danganronpa-online/public-gmod#383]
### Что наблюдается?

При использовании фонарика, его модель не отображается на руках и со стороны, но работает корректно.

https://user-images.githubusercontent.com/40503335/147891167-b5d335a2-e68d-4e51-9f35-4dafd79da989.mp4

### Как это должно работать?

Модель фонарика должна отображаться.

### Как это повторить?

1) Заспавнить фонарик любым способом
2) Увидеть ошибку вместо фонарика

### Обратная связь

NeverLucky#6572

**Comment by mikvoin** [comment]
Исправлено
