### ISSUE TITLE
Q меню Джунко Эношимы

### ISSUE THREAD

**Issue by cherrymiki** [danganronpa-online/public-gmod#390]
### Что наблюдается?

В Q меню у персонажа Джунко Эношима нет иконки 
![image](https://user-images.githubusercontent.com/93860852/149794378-96f43266-6e7f-449e-9277-6ce2147f9500.png)

### Как это должно работать?

должна?

### Как это повторить?

взять персонажа и открыть q меню

### Обратная связь

Отвечу здесь.

**Comment by mikvoin** [comment]
Исправлено
