### ISSUE TITLE
Не удаляющийся проп - Вентилятор

### ISSUE THREAD

**Issue by 1TheHacker** [danganronpa-online/public-gmod#391]
### Что наблюдается?

Вентилятор в прачечной на Основной Сервер 4 - не удаляется, так же было и на Сервере 3.
Он существует как визуальный объект и не имеет никакой коллизий.
![изображение](https://user-images.githubusercontent.com/97951905/149926023-d8cf0d50-a10d-464b-ae21-9296dd34ac1d.png)
![изображение](https://user-images.githubusercontent.com/97951905/149926088-3095e513-d250-4d0e-bcc1-05418daae545.png)

### Как это должно работать?

Данный проп должен удаляться.

### Как это повторить?

Зайти на Сервер 3 или 4 и попытаться его удалить.

### Ошибки в консоли

```shell
Ошибок в консоле не наблюдается.
```

### Обратная связь

TheHacker#1604

**Comment by mikvoin** [comment]
Исправлено
