### ISSUE TITLE
Иконка фонарика - Error

### ISSUE THREAD

**Issue by SaintKrou** [danganronpa-online/public-gmod#392]
### Что наблюдается?

В гарис модовском инвентаре у фонарика иконка - Error
https://i.imgur.com/TEOdBka.png

### Как это должно работать?

Должна быть другая иконка, либо иконка по умолчанию (https://i.imgur.com/kUwg2aU.png)

### Как это повторить?

1) Взять фонарик
2) Покрутить колесиком

### Обратная связь

Krou#2034

**Comment by mikvoin** [comment]
Исправлено
