### ISSUE TITLE
Спрайты Кёко Киригири.

### ISSUE THREAD

**Issue by cherrymiki** [danganronpa-online/public-gmod#393]
### Что наблюдается?

Спрайты, нарисованные нашими художниками, как я понимаю, отображаются как эмотекстуры. Если переключить на них, будут те же самые эмотекстуры.
![image](https://user-images.githubusercontent.com/93860852/150169112-4f76a1f8-6494-40b3-8898-eaf6a8248b29.png)

### Как это должно работать?

Спрайтов либо не должно быть, либо должны быть исправлены

### Как это повторить?

Взять Киригири, запустить суд, прокрутить в самый вниз в листе спрайтов, включить любой спрайт.

### Обратная связь

Отвечу здесь.

**Comment by mikvoin** [comment]
Исправлено
