### ISSUE TITLE
Ошибка вывода улик в интерфейсе суда и монопода.

### ISSUE THREAD

**Issue by Ge5akl** [danganronpa-online/public-gmod#394]
### Что наблюдается?

Если человеку, который имеет статус наблюдателя выдать монопод - то во время предоставления улики появляются ошибки и дальнейшее прекращение вывода  этих предоставляемых улик в интерфейсе.
Видео с воспроизведением ошибки: https://youtu.be/u6TkyKJ5PVQ

### Как это должно работать?

Сделать проверку аргумента на неопределенность.

### Как это повторить?

1) Выдать игроку, который не находится в наблюдателях монопод. 
2) Включить суд
3) Предоставить улику.

### Ошибки в консоли

```shell
На видео все подробно показал.
```

### Обратная связь

eConf1g#7954

**Comment by SaintKrou** [comment]
Проблема связана с тем, что на голове ты не исследовал ни одной улики, а не с монопадом. Дубликат #26
