### ISSUE TITLE
Гильзы патронов - Error

### ISSUE THREAD

**Issue by SaintKrou** [danganronpa-online/public-gmod#395]
### Что наблюдается?

У оружия во вкладке [DRO] Огнестрельное оружие баг, при котором, если у оружия после выстрела выпадает гильза (это не у всех), то в таком случае вместо гильзы выпадает Error
(Скриншот - результат стрельбы с MAC-10)
![image](https://user-images.githubusercontent.com/91148905/150511034-3dd946b5-5126-4384-9f4d-f0d583e64204.png)

### Как это должно работать?

У гильз должна быть правильная модель

### Как это повторить?

1) Выбрать оружие из вкладки [DRO] Огнестрельное оружие
2) Выстрелить
3) Если проблемы нет, то значит у оружия просто не выпадают гильзы. Надо сменить на другое оружие

### Обратная связь

Krou#2034

**Comment by mikvoin** [comment]
Исправлено
