### ISSUE TITLE
Баг с отображением ошибки спрайта Шуичи Сайхары в конце раунда.

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#43]
In GitLab by @Eleon on Mar 26, 2021, 22:27

● Сервер: Dev

● Карта: dro_hopespeak

● Описание: После запуска EndRound, в самом EndRound-е персонаж Шуичи Сайхара отображается ошибкой (типичные чёрно-розовые пиксели). Перед следующим судом Куратор два энд-раунда запускал для теста, но ошибка всё оставалась. После этого мы снова взяли Шуичи, но эрорки уже не было.

● Сценарий: 1. Взять персонажа Шуичи Сайхара в каст. 2. Запустить EndRound, 3. Данная ошибка воспроизводиться

● Классификация: Minor

● Видео: https://youtu.be/_LA_jy4-C2o

**Comment by octothorpteam** [comment]
In GitLab by @Eleon on Mar 26, 2021, 22:32

changed the description

**Comment by SaintKrou** [comment]
Баг связан не с Шуичи, а со смертью Монокумой. Этот баг актуален, но не здесь, [а тут](https://github.com/danganronpa-online/public-gmod/issues/61). Здесь же его следует закрыть

**Comment by mikvoin** [comment]
Дубликат #61
