### ISSUE TITLE
Фиолетовая Комару

### ISSUE THREAD

**Issue by octothorpteam** [danganronpa-online/public-gmod#88]
In GitLab by @Lenka on Jun 2, 2021, 21:28

Есть редкий баг, который был ещё с января, при котором Комару становится фиолетовой
В данном случае фиолетовый оттенок видео только на мне
![Безымянный](/uploads/1d8866f4e7d65cde633513ae5640eb9d/Безымянный.png)

**Comment by octothorpteam** [comment]
In GitLab by @Lenka on Jun 2, 2021, 21:30

changed the description

**Comment by octothorpteam** [comment]
In GitLab by @Lenka on Jun 2, 2021, 21:38

changed the description

**Comment by Jewaramir** [comment]
![image](https://user-images.githubusercontent.com/56727770/138929171-9222940a-f6a5-47d8-a742-eedafbdf4571.png)

**Comment by mikvoin** [comment]
@LenkaYandere, может ли быть такое, что у тебя измененная версия модели? Я так понимаю, что она розовая из-за того, что не может определить lightwrap. Проверь корневую папку и папку с аддонами.

**Comment by Jewaramir** [comment]
@mikvoin я понял проблему, просто был конфликт между двумя аддонами, сейчас такое не должно проявляться
